services:
  backend:
    build:
      context: .
      dockerfile: backend/Dotnet_Organizer/Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Angular_Organizer/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
